Introduction to Pytorch

In [1]:
import torch

In [4]:
print(torch.__version__)


2.7.0


TENSORS IN PYTORCH

In [15]:
# Create Tensors

a=torch.empty(2, 3)  # 2x3 tensor with uninitialized data
type(a)

b=torch.zeros(2, 3)  # 2x3 tensor filled with zeros
print(b)

c=torch.ones(2, 3)  # 2x3 tensor filled with ones
print(c)

d=torch.rand(2, 3)  # 2x3 tensor filled with random numbers from a uniform distribution
print(d)

torch.manual_seed(10)  # Set the random seed for reproducibility
e=torch.rand(2, 3)  # 2x3 tensor filled with random numbers from a uniform distribution
print(e)

f=torch.tensor(([1,2,3,4],[5,6,7,8]))  # Create a tensor from a list
print(f)


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])
tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [16]:
a.shape

torch.Size([2, 3])

In [19]:
a.dtype

torch.float32

In [20]:
b=torch.tensor(([1,3,4,5],[5,6,7,8]), dtype=torch.int32)  # Create a tensor with a specific data type
print(b)

tensor([[1, 3, 4, 5],
        [5, 6, 7, 8]], dtype=torch.int32)


In [22]:
i=torch.rand_like(a,dtype=torch.float32)  # Create a tensor with the same size as x but with random values

print(i)

tensor([[0.6938, 0.9693, 0.6178],
        [0.3304, 0.5479, 0.4440]])


In [26]:
# Mathematical Operations
x=torch.rand(2, 3)
print(x)


tensor([[0.8067, 0.8379, 0.7694],
        [0.6694, 0.7203, 0.2235]])


In [ ]:
# Addition
print(x+1)

# Subtraction
print(x-1)

# Multiplication
print(x*2)

# Division
print(x/2)

# integer division
print(x*10 //2)

# Modulus
print(x*10 % 3)

# Power
print(x**2)

tensor([[1.8067, 1.8379, 1.7694],
        [1.6694, 1.7203, 1.2235]])
tensor([[-0.1933, -0.1621, -0.2306],
        [-0.3306, -0.2797, -0.7765]])
tensor([[1.6133, 1.6757, 1.5387],
        [1.3388, 1.4405, 0.4470]])
tensor([[0.4033, 0.4189, 0.3847],
        [0.3347, 0.3601, 0.1117]])
tensor([[4., 4., 3.],
        [3., 3., 1.]])


In [33]:
a=torch.tensor(([1,2,3],[4,5,6]))
b=torch.tensor(([-7,-8,9],[10,-11,12]))

print(torch.neg(a))  # Negation

tensor([[-1, -2, -3],
        [-4, -5, -6]])


In [ ]:
# Reduction Operations

a=torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
print(a)
print(a.sum())  # Sum of all elements
print(a.sum(dim=0))  # Sum along the first dimension (columns) 
print(a.sum(dim=1))  # Sum along the second dimension (rows)
print(torch.mean(a))  # Mean of all elements
print(torch.max(a))  # Maximum value
print(torch.min(a))  # Minimum value
print(torch.prod(a))  # Product of all elements
print(torch.std(a))  # Standard deviation
print(torch.var(a))  # Variance
print(torch.median(a))  # Median
print(torch.argmax(a))  # Index of the maximum value
print(torch.argmin(a))  # Index of the minimum value


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor(3.5000)
tensor(6.)
tensor(1.)
tensor(720.)
tensor(1.8708)
tensor(3.5000)
tensor(3.)
tensor(5)
tensor(0)


In [49]:
# Matrix Operations

a=torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
b=torch.tensor(([7,8,9],[10,11,12]),dtype=torch.float32)

print(torch.transpose(a,0,1))  # Transpose of a matrix


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [56]:
# Special Functions

a=torch.tensor(([-1,0,1,2,3,4]))

print(torch.exp(a))  # Exponential function
print(torch.log(a))  # Natural logarithm
print(torch.sqrt(a))  # Square root
print(torch.sin(a))  # Sine function
print(torch.cos(a))  # Cosine function
print(torch.sigmoid(a)) #Sigmoid function
print(torch.relu(a)) #Rectified Linear Unit function

tensor([ 0.3679,  1.0000,  2.7183,  7.3891, 20.0855, 54.5982])
tensor([   nan,   -inf, 0.0000, 0.6931, 1.0986, 1.3863])
tensor([   nan, 0.0000, 1.0000, 1.4142, 1.7321, 2.0000])
tensor([-0.8415,  0.0000,  0.8415,  0.9093,  0.1411, -0.7568])
tensor([ 0.5403,  1.0000,  0.5403, -0.4161, -0.9900, -0.6536])
tensor([0.2689, 0.5000, 0.7311, 0.8808, 0.9526, 0.9820])
tensor([0, 0, 1, 2, 3, 4])


In [ ]:
# For inplace changes add an underscore to the function name
# Example
a=torch.tensor(([1,2,3],[4,5,6]),dtype=torch.float32)
print(a)
a.add_(1)  # In-place addition
print(a)
a.sub_(1)  # In-place subtraction
print(a)
a.mul_(2)  # In-place multiplication
print(a)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


AUTOGRAD IN PYTORCH

In [ ]:
x=torch.tensor(3.0,requires_grad=True)  # Create a tensor with gradient tracking
y=x**2



tensor(9., grad_fn=<PowBackward0>)


In [61]:
y.backward()  # Compute the gradient
print(x.grad)  # Print the gradient

tensor(6.)


In [65]:
x=torch.tensor(4.0,requires_grad=True)  # Create a tensor with gradient tracking
y=x**2
z=torch.sin(y)  # Create another tensor
z.backward()  # Compute the gradient
print(x.grad)  # Print the gradient

tensor(-7.6613)


In [ ]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

z=w*x+b  # Linear equation
y_pred=torch.sigmoid(z)  # Sigmoid activation function
loss=torch.nn.functional.binary_cross_entropy(y_pred,y)  # Binary cross-entropy loss

loss.backward()  # Compute the gradient
print(w.grad)  # Print the gradient of w
print(b.grad)  # Print the gradient of b

w.grad.zero_()  # Zero the gradients->Avoid gradient accumulation
b.grad.zero_()  # Zero the gradients->Avoid gradient accumulation

tensor(6.6918)
tensor(0.9988)


tensor(0.)